version: "3.7"
services:
  points:
    container_name: auth-logistic
    build: .
    image: auth-logistic:2.0
    ports:
      - "3000"
    environment:
      - DB_HOST=${DB_HOST:?err}
      - DB_USER=${DB_USER:?err}
      - DB_NAME=${DB_NAME:?err}
      - DB_PORT=${DB_PORT:?err}
      - DB_PASSWORD=${DB_PASSWORD:?err}
      - JWT_SECRET=${JWT_SECRET:?err}